import assert from "node:assert/strict";
import { test } from "node:test";
import {
  assessRepoRootForPublish,
  buildOpenPagesReadme,
  createOpenPagesSiteManifest,
  looksLikeOpenPagesPublishedContent,
  OPEN_PAGES_SOURCE_URL,
  parseOpenPagesSiteManifest,
  repoRootLooksEmpty,
  repoRootLooksForeign,
  serializeOpenPagesSiteManifest,
} from "./site-manifest.js";

test("parseOpenPagesSiteManifest accepts valid manifest", () => {
  const raw = serializeOpenPagesSiteManifest(createOpenPagesSiteManifest("default"));
  const parsed = parseOpenPagesSiteManifest(raw);
  assert.equal(parsed?.siteId, "default");
  assert.equal(parsed?.schema, "open-pages.site/v1");
});

test("parseOpenPagesSiteManifest keeps optional theme and addons", () => {
  const raw = serializeOpenPagesSiteManifest(
    createOpenPagesSiteManifest("default", {
      theme: "cocofhu",
      addons: [{ kind: "theme", source: "cocofhu/cocofhu-theme", enabled: true }],
    }),
  );
  const parsed = parseOpenPagesSiteManifest(raw);
  assert.equal(parsed?.theme, "cocofhu");
  assert.equal(parsed?.addons?.[0]?.source, "cocofhu/cocofhu-theme");
});

test("assessRepoRootForPublish blocks foreign repos without manifest", () => {
  const check = assessRepoRootForPublish({
    siteId: "default",
    manifestRaw: null,
    rootEntries: ["README.md", "_config.yml", "source"],
  });
  assert.equal(check.eligible, false);
  assert.equal(check.reason, "foreign");
});

test("assessRepoRootForPublish allows a previous Open Pages publish without manifest", () => {
  const check = assessRepoRootForPublish({
    siteId: "default",
    manifestRaw: null,
    rootEntries: ["README.md", "_config.yml", "source"],
    configYaml: "# generated by Open Pages\ntheme: landscape\n",
  });
  assert.equal(check.eligible, true);
  assert.equal(check.reason, "adoptable");
});

test("assessRepoRootForPublish allows a previous Open Pages README without manifest", () => {
  const check = assessRepoRootForPublish({
    siteId: "default",
    manifestRaw: null,
    rootEntries: ["README.md", "_config.yml", "source"],
    readme: buildOpenPagesReadme({
      title: "Open Pages",
      pagesUrl: "https://cocofhu.github.io/just-test/",
      owner: "cocofhu",
      repo: "just-test",
    }),
  });
  assert.equal(check.eligible, true);
  assert.equal(check.reason, "adoptable");
});

test("looksLikeOpenPagesPublishedContent requires our own markers", () => {
  assert.equal(looksLikeOpenPagesPublishedContent({ configYaml: "theme: next\n" }), false);
  assert.equal(looksLikeOpenPagesPublishedContent({ readme: "# My blog\n" }), false);
  assert.equal(
    looksLikeOpenPagesPublishedContent({ configYaml: "# generated by Open Pages\n" }),
    true,
  );
});

test("assessRepoRootForPublish allows adoptable empty repo", () => {
  const check = assessRepoRootForPublish({
    siteId: "default",
    manifestRaw: null,
    rootEntries: ["README.md"],
  });
  assert.equal(check.eligible, true);
  assert.equal(check.reason, "adoptable");
});

test("assessRepoRootForPublish blocks a code repo that is not Open Pages", () => {
  const check = assessRepoRootForPublish({
    siteId: "default",
    manifestRaw: null,
    rootEntries: ["README.md", "src", "Cargo.toml"],
  });
  assert.equal(check.eligible, false);
  assert.equal(check.reason, "foreign");
});

test("repoRootLooksEmpty allows only new-repo files", () => {
  assert.equal(repoRootLooksEmpty(["README.md", "LICENSE", ".gitignore"]), true);
  assert.equal(repoRootLooksEmpty(["README.md", "src"]), false);
});

test("assessRepoRootForPublish blocks mismatched manifest siteId", () => {
  const raw = serializeOpenPagesSiteManifest(createOpenPagesSiteManifest("other-site"));
  const check = assessRepoRootForPublish({
    siteId: "default",
    manifestRaw: raw,
    rootEntries: ["manifest.json", "_config.yml"],
  });
  assert.equal(check.eligible, false);
  assert.equal(check.reason, "bound-other");
});

test("origin snapshot paths are not treated as pages", async () => {
  const { fileKind, isOriginPath, originSnapshotPath } = await import("./index.js");
  assert.equal(isOriginPath("source/origin/_config.yml"), true);
  assert.equal(originSnapshotPath("_config.yml"), "source/origin/_config.yml");
  assert.equal(fileKind("source/origin/source/about/index.md"), "other");
  assert.equal(fileKind("source/about/index.md"), "page");
});

test("repoRootLooksForeign detects hexo markers", () => {
  assert.equal(repoRootLooksForeign(["README.md"]), false);
  assert.equal(repoRootLooksForeign(["package.json"]), true);
});

test("buildOpenPagesReadme includes site info and project link", () => {
  const md = buildOpenPagesReadme({
    title: "Open Pages",
    description: "Write, preview, publish",
    pagesUrl: "https://cocofhu.github.io/just-test/",
    theme: "next",
    owner: "cocofhu",
    repo: "just-test",
  });
  assert.match(md, /^# Open Pages/m);
  assert.match(md, /Write, preview, publish/);
  assert.match(md, /https:\/\/cocofhu\.github\.io\/just-test\//);
  assert.match(md, /https:\/\/github\.com\/cocofhu\/just-test/);
  assert.match(md, /\*\*主题\*\*：next/);
  assert.match(md, new RegExp(OPEN_PAGES_SOURCE_URL.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
});
